# Item schema

# --- !Ups

CREATE TABLE ITEM (
    ID BIGSERIAL PRIMARY KEY,
    ITEM_NUMBER TEXT NOT NULL UNIQUE,
    CATEGORY TEXT NOT NULL,
    DONOR TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    MINBID MONEY NOT NULL,
    ESTVALUE MONEY NOT NULL
);

# --- !Downs

DROP TABLE ITEM;
