# Winning Bid schema

# --- !Ups

CREATE TABLE WINNINGBID (
    ID BIGSERIAL PRIMARY KEY,
    BIDDER_ID BIGINT REFERENCES BIDDER (ID) ON DELETE RESTRICT,
    ITEM_ID BIGINT REFERENCES ITEM (ID) ON DELETE RESTRICT,
    AMOUNT MONEY NOT NULL
);

# --- !Downs

DROP TABLE WINNINGBID;
