# Bidder SCHEMA

# --- !Ups

CREATE TABLE BIDDER (
  ID       BIGSERIAL PRIMARY KEY,
  EVENT_ID BIGINT REFERENCES EVENT (ID) ON DELETE RESTRICT,
  NAME     TEXT NOT NULL UNIQUE
);

# --- !Downs

DROP TABLE BIDDER;
