
# --- !Ups

CREATE TABLE ORGANIZATION (
  ID   BIGSERIAL PRIMARY KEY,
  NAME TEXT NOT NULL UNIQUE
);
CREATE TABLE EVENT (
  ID              BIGSERIAL PRIMARY KEY,
  ORGANIZATION_ID BIGINT REFERENCES ORGANIZATION (ID) ON DELETE RESTRICT,
  NAME            TEXT NOT NULL,
  UNIQUE (ORGANIZATION_ID, NAME)
);
CREATE TABLE CONTACT (
  ID              BIGSERIAL PRIMARY KEY,
  ORGANIZATION_ID BIGINT REFERENCES ORGANIZATION (ID) ON DELETE RESTRICT,
  NAME            TEXT NOT NULL,
  PHONE           TEXT,
  EMAIL           TEXT,
  UNIQUE (ORGANIZATION_ID, NAME)
);
CREATE TABLE BIDDER (
  ID            BIGSERIAL PRIMARY KEY,
  EVENT_ID      BIGINT REFERENCES EVENT (ID) ON DELETE RESTRICT,
  BIDDER_NUMBER TEXT NOT NULL,
  CONTACT_ID    BIGINT REFERENCES CONTACT (ID) ON DELETE RESTRICT,
  UNIQUE (EVENT_ID, BIDDER_NUMBER)
);
CREATE TABLE ITEM (
  ID          BIGSERIAL PRIMARY KEY,
  EVENT_ID    BIGINT REFERENCES EVENT (ID) ON DELETE RESTRICT,
  ITEM_NUMBER TEXT  NOT NULL UNIQUE,
  DESCRIPTION TEXT  NOT NULL,
  MINBID      MONEY NOT NULL
);
CREATE TABLE PAYMENT (
  ID          BIGSERIAL PRIMARY KEY,
  BIDDER_ID   BIGINT REFERENCES BIDDER (ID) ON DELETE RESTRICT,
  DESCRIPTION TEXT  NOT NULL,
  AMOUNT      MONEY NOT NULL
);
CREATE TABLE BID (
  ID        BIGSERIAL PRIMARY KEY,
  BIDDER_ID BIGINT REFERENCES BIDDER (ID) ON DELETE RESTRICT,
  ITEM_ID   BIGINT REFERENCES ITEM (ID) ON DELETE RESTRICT,
  AMOUNT    MONEY NOT NULL
);

# --- !Downs

DROP TABLE BID;
DROP TABLE PAYMENT;
DROP TABLE ITEM;
DROP TABLE BIDDER;
DROP TABLE CONTACT;
DROP TABLE EVENT;
DROP TABLE ORGANIZATION;
