# Bidder SCHEMA

# --- !Ups

CREATE TABLE BIDDER (
  ID            BIGSERIAL PRIMARY KEY,
  EVENT_ID      BIGINT REFERENCES EVENT (ID) ON DELETE RESTRICT,
  BIDDER_NUMBER TEXT NOT NULL,
  CONTACT_ID    BIGINT REFERENCES CONTACT (ID) ON DELETE RESTRICT,
  UNIQUE (EVENT_ID, BIDDER_NUMBER)
);

# --- !Downs

DROP TABLE BIDDER;
