# Item SCHEMA

# --- !Ups

CREATE TABLE ITEM (
  ID          BIGSERIAL PRIMARY KEY,
  EVENT_ID    BIGINT REFERENCES EVENT (ID) ON DELETE RESTRICT,
  ITEM_NUMBER TEXT  NOT NULL UNIQUE,
  DESCRIPTION TEXT  NOT NULL,
  MINBID      MONEY NOT NULL
);

# --- !Downs

DROP TABLE ITEM;
