# Bid SCHEMA

# --- !Ups

CREATE TABLE BID (
  ID        BIGSERIAL PRIMARY KEY,
  BIDDER_ID BIGINT REFERENCES BIDDER (ID) ON DELETE RESTRICT,
  ITEM_ID   BIGINT REFERENCES ITEM (ID) ON DELETE RESTRICT,
  AMOUNT    MONEY NOT NULL
);

# --- !Downs

DROP TABLE BID;
