# EVENT SCHEMA

# --- !Ups

CREATE TABLE EVENT (
  ID              BIGSERIAL PRIMARY KEY,
  ORGANIZATION_ID BIGINT REFERENCES ORGANIZATION (ID) ON DELETE RESTRICT,
  NAME            TEXT NOT NULL,
  UNIQUE (ORGANIZATION_ID, NAME)
);

# --- !Downs

DROP TABLE EVENT;
