# Contact SCHEMA

# --- !Ups

CREATE TABLE CONTACT (
  ID              BIGSERIAL PRIMARY KEY,
  ORGANIZATION_ID BIGINT REFERENCES ORGANIZATION (ID) ON DELETE RESTRICT,
  NAME            TEXT NOT NULL,
  PHONE           TEXT,
  EMAIL           TEXT,
  UNIQUE (ORGANIZATION_ID, NAME)
)