# Item schema

# --- !Ups

CREATE TABLE ITEM (
    ID BIGINT IDENTITY(1) PRIMARY KEY,
    ITEM_NUMBER VARCHAR(15) NOT NULL UNIQUE,
    CATEGORY VARCHAR(63) NOT NULL,
    DONOR VARCHAR(63) NOT NULL,
    DESCRIPTION VARCHAR(1023) NOT NULL,
    MINBID DECIMAL(20, 2) NOT NULL,
    ESTVALUE DECIMAL(20, 2) NOT NULL
);

# --- !Downs

DROP TABLE ITEM;
